name             'wcsprov'
maintainer       'Wizzie Analytics'
maintainer_email 'devel@wizzie.io'
license          'All rights reserved'
description      'Provision WCS Marketplace AMI'
version          '0.0.1'
